# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Category
  items:
    - label: 'Display'
      link: '/category/display'
    - label: 'Position'
      link: '/category/position'
    - label: 'Flex'
      link: '/category/flex'
    - label: 'Grid'
      link: '/category/grid'
