version: "3.1"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${ROOT_DIR}:/usr/share/nginx/html
    ports:
      - 8080:80

  myhttpd:
    image: myhttpd:latest
    build:
      context: .
    volumes:
      - ${ROOT_DIR}:/myhttpd/root
    ports:
      - 8080:80
