listen: 80
server_name: 0.0.0.0
root: ./root
index: index.html
error_pages:
  404: ./root/404.html
  500: ./root/50X.html
types:
  text/html:
    - html
    - htm
    - shtml
  text/css:
    - css
  image/gif:
    - gif
  image/png:
    - png
  image/jpeg:
    - jpeg
    - jpg
  image/svg+xml:
    - svg
    - svgz
  image/x-icon:
    - ico
  text/plain:
    - txt
  text/xml:
    - xml
  application/javascript:
    - js
  application/json:
    - json
    - map
  application/wasm:
    - wasm
gzip:
  enabled: true
  comp_level: 6
  min_length: 0
  types:
    - text/html
    - text/css
    - image/gif
    - image/svg+xml
    - text/plain
    - text/xml
    - application/javascript
    - application/json
    - application/wasm
buffer_size: 16384
