listen: 8080
server_name: localhost
root: ./root
index: index.html
error_pages:
  404: 404.html
  500: 50X.html
types:
  text/html:
    - html
    - htm
    - shtml
  text/css:
    - css
  image/gif:
    - gif
  image/png:
    - png
  image/jpeg:
    - jpeg
    - jpg
  image/svg+xml:
    - svg
    - svgz
  text/plain:
    - txt
  text/xml:
    - xml
  application/javascript:
    - js
  application/json:
    - json
  application/wasm:
    - wasm
