version: '3.8'

services:
  go:
    image: golang:1.17beta1-buster
    volumes:
      - ./:/home
    working_dir: /home
    environment:
      - GOFLAGS=-gcflags=-G=3
    command: go build -o build/main main.go && build/main
